export const stripThemes = {
  classic: {
    label: "Classic Booth",
    description: "Warm, clean, and timeless",
    background: "#fffdf9",
    foreground: "#182033",
    accent: "#f05a67",
    panel: "#f5eee8",
    badgeForeground: "#ffffff",
    motif: "clean",
  },
  pink: {
    label: "Pink Pop",
    description: "Bold candy color and confetti",
    background: "#f05a67",
    foreground: "#ffffff",
    accent: "#ffd166",
    panel: "#ffd9de",
    badgeForeground: "#182033",
    motif: "confetti",
  },
  midnight: {
    label: "Midnight",
    description: "Deep navy with violet stars",
    background: "#182033",
    foreground: "#fff8f1",
    accent: "#9d87ff",
    panel: "#2b3450",
    badgeForeground: "#ffffff",
    motif: "stars",
  },
  lavender: {
    label: "Lavender Dream",
    description: "Soft lilac and little hearts",
    background: "#eee8ff",
    foreground: "#33245d",
    accent: "#7c5cfc",
    panel: "#d9ceff",
    badgeForeground: "#ffffff",
    motif: "hearts",
  },
  film: {
    label: "Retro Film",
    description: "Analog black with amber details",
    background: "#171717",
    foreground: "#f8e9c8",
    accent: "#e6a83e",
    panel: "#34302a",
    badgeForeground: "#171717",
    motif: "film",
  },
  mint: {
    label: "Mint Day",
    description: "Fresh green with playful dots",
    background: "#e1f5ec",
    foreground: "#174e3a",
    accent: "#1c9b6d",
    panel: "#bde5d3",
    badgeForeground: "#ffffff",
    motif: "dots",
  },
  sunshine: {
    label: "Sunshine",
    description: "Golden, bright, and celebratory",
    background: "#fff2b8",
    foreground: "#543b0b",
    accent: "#ef7d32",
    panel: "#ffd66b",
    badgeForeground: "#ffffff",
    motif: "rays",
  },
  mono: {
    label: "Monochrome",
    description: "Editorial black and white",
    background: "#f4f4f2",
    foreground: "#111111",
    accent: "#111111",
    panel: "#d7d7d3",
    badgeForeground: "#ffffff",
    motif: "frame",
  },
} as const;

export type StripThemeId = keyof typeof stripThemes;
